# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      # Use "run-command" to execute custom MATLAB scripts, functions, or statement
      - name: Run tests with run-command action
        uses: matlab-actions/run-command@v2
        command: disp('Running my custom testing procedure!'); addpath('code'); results = runtests('IncludeSubfolders', true); assertSuccess(results);

      # Runs a set of commands using the runners shell
      # Use "run-test" to automatically run tests authored using the MATLAB unit testing framework or Simulink Test™
      - name: Run test with run-tests action
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: code

      # Use "run-build" to invoke the MATLAB build tool and run build tasks
      - name: Run tests with default build tool task
        uses: matlab-actions/run-build@v2


      